// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wasted.API.Data;

namespace WastedAPI.Migrations
{
    [DbContext(typeof(WastedContext))]
    partial class WastedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wasted.API.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("numberOfIngredients")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ingredients = "unknown",
                            Name = "Chocolate Cake",
                            Type = "Baked",
                            numberOfIngredients = 4
                        },
                        new
                        {
                            Id = 2,
                            Ingredients = "unknown",
                            Name = "Brownies",
                            Type = "Baked",
                            numberOfIngredients = 5
                        });
                });

            modelBuilder.Entity("Wasted.API.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Wasted.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("EnergyValue")
                        .HasColumnType("float");

                    b.Property<string>("MeasurementUnits")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnergyValue = 158.48699999999999,
                            MeasurementUnits = "kg",
                            Name = "Apple",
                            Type = "Fruit"
                        },
                        new
                        {
                            Id = 2,
                            EnergyValue = 284.54599999999999,
                            MeasurementUnits = "kg",
                            Name = "Troat",
                            Type = "Fish"
                        },
                        new
                        {
                            Id = 3,
                            EnergyValue = 120.69199999999999,
                            MeasurementUnits = "g",
                            Name = "Orange",
                            Type = "Fruit"
                        },
                        new
                        {
                            Id = 4,
                            EnergyValue = 262.178,
                            MeasurementUnits = "kg",
                            Name = "Blackberry",
                            Type = "Berry"
                        },
                        new
                        {
                            Id = 5,
                            EnergyValue = 352.69799999999998,
                            MeasurementUnits = "kg",
                            Name = "Cheese",
                            Type = "Dairy"
                        },
                        new
                        {
                            Id = 6,
                            EnergyValue = 271.745,
                            MeasurementUnits = "kg",
                            Name = "Bass",
                            Type = "Fish"
                        },
                        new
                        {
                            Id = 7,
                            EnergyValue = 175.12450000000001,
                            MeasurementUnits = "l",
                            Name = "Buttermilk",
                            Type = "Dairy"
                        });
                });

            modelBuilder.Entity("Wasted.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
